Add lint presubmit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -50,5 +50,13 @@ fi
 exec cfx xpi
 exec git add blushproof.xpi
 
+for f in `git diff-index --name-only ${against} -- | egrep *.py`; do
+  pylint $f
+  if [ $? != 0 ]
+    echo "Lint checks failed"
+    exit 1
+  fi
+done  
+
 # If there are whitespace errors, print the offending file names and fail.
 exec git diff-index --check --cached $against --
